[package]
name = "zirk-codegen-llvm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
zirk-diagnostics.workspace = true
zirk-ir.workspace = true

inkwell = { version = "0.10", default-features = false, features = ["llvm20-1"] }
